"""
OD-based Node Initialization via Virtual Edge Embedding Aggregation.

This module implements the core feature initialization scheme of the GUIDED framework.
Instead of relying on transductive node IDs or spatial coordinates, GUIDED derives initial
node representations purely from Origin-Destination (OD) travel demand patterns.

Methodology:
1. Virtual links e_q = (u, v) are constructed for every active OD pair with scalar demand d_q.
2. An EdgeProcessor (Linear MLP or RBF) maps scalar demand d_q to a 32-dim embedding e_q.
3. ODNodeInitializer aggregates outgoing embeddings (e_q where u=v) and incoming embeddings
   (e_q where v=v) across all connected virtual links using directional scatter-sum operations:
     H_out[v] = sum_{q: u=v} e_q
     H_in[v]  = sum_{q: v=v} e_q
4. The two directional representations are concatenated into a 64-dim node feature vector:
     x_v^(0) = [H_out[v] || H_in[v]] in R^64
This formulation makes initial node embeddings invariant to graph layout and node permutation,
enabling direct spatial transferability across distinct road networks.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Self

import torch
import torch.nn as nn
from torch_geometric.data import HeteroData
from torch_geometric.utils import scatter

from ml_static.models.base import BaseConfig
from ml_static.utils.validation import validate_edge_attribute


@dataclass(frozen=True)
class ODNodeInitializerConfig(BaseConfig):
    """Configuration schema for OD-based node initialization."""

    @classmethod
    def from_dict(cls, data: dict) -> Self:
        """Factory method to create OD node initializer configuration."""
        return cls()

    def validate(self) -> None:
        """Validate configuration parameters."""
        pass


class ODNodeInitializer(nn.Module):
    """
    Aggregates virtual OD edge embeddings into initial physical node features.

    Architecture Details:
    - Input: Virtual edge embeddings e_q in R^32 generated by EdgeProcessor (Linear or RBF).
    - Source aggregation (H_out): Scatter-sum of outgoing virtual link embeddings originating at node v.
    - Target aggregation (H_in): Scatter-sum of incoming virtual link embeddings terminating at node v.
    - Output: Node feature matrix x_v in R^(N x 64), where N is the total number of physical nodes.
    """

    def __init__(self) -> None:
        super().__init__()

    def forward(
        self,
        x: torch.Tensor | None,
        data: HeteroData,
        edge_type: tuple | str = ("nodes", "virtual", "nodes"),
    ) -> HeteroData:
        """
        Aggregates virtual edge demand embeddings into physical node features.

        Args:
            x: Must be None for 'from_demand' initialization (node features are synthesized dynamically).
            data: Heterogeneous PyG data object containing virtual edge_index and edge_embedding.
            edge_type: PyG edge type tuple for virtual links (default: ("nodes", "virtual", "nodes")).

        Returns:
            Updated HeteroData object with synthesized node features assigned to data["nodes"].x [N, 64].
        """
        # Validate that input x is None (GUIDED constructs initial features dynamically from demand)
        if x is not None:
            raise ValueError(
                "Input `x` must be None for ODNodeInitializer. "
                "Node features are dynamically synthesized from virtual edge embeddings."
            )

        # Validate edge index and edge embedding tensors
        validate_edge_attribute(data, edge_type, "edge_index", expected_ndim=2)
        validate_edge_attribute(data, edge_type, "edge_embedding", expected_ndim=2)

        edge_index = data[edge_type].edge_index
        edge_emb = data[edge_type].edge_embedding

        # Determine total physical node count in the graph topology
        num_nodes = getattr(data["nodes"], "num_nodes", None)
        if num_nodes is None:
            num_nodes = data["nodes"].net_demand.size(0)

        # 1. Scatter-sum outgoing OD embeddings (source nodes = edge_index[0])
        # Nodes without outgoing OD activity automatically receive zero-tensors of dim 32
        H_out = scatter(edge_emb, edge_index[0], dim=0, dim_size=num_nodes, reduce="sum")

        # 2. Scatter-sum incoming OD embeddings (target nodes = edge_index[1])
        # Nodes without incoming OD activity automatically receive zero-tensors of dim 32
        H_in = scatter(edge_emb, edge_index[1], dim=0, dim_size=num_nodes, reduce="sum")

        # 3. Concatenate directional embeddings: [H_out || H_in] -> [N, 64]
        # This provides both origin activity and destination activity contexts for each physical node
        data["nodes"].x = torch.cat([H_out, H_in], dim=1)

        return data

    @classmethod
    def from_config(cls, config: ODNodeInitializerConfig) -> Self:
        """Create ODNodeInitializer instance from configuration object."""
        config.validate()
        return cls()
